In [1]:
!pip install simpy

In [2]:
#imports
import numpy as np
import random as rm
import simpy

In [43]:
#initializations/ Parameters
n=10
c= np.zeros([n,n], dtype = int)
num_of_mine=10
i=0
while i<num_of_mine:
    x= rm.randint(0,n-1)
    y= rm.randint(0,n-1)
    if c[x][y] == -10000:
        continue
    else: 
        c[x][y] = "null"
        i+=1
c

ValueError: invalid literal for int() with base 10: 'null'

In [64]:
def iterations(num_of_itr, n,num_of_mines): #num_of _itr is how many time you want "me" to move around, n is to get matrix of size nxn

    matrix= np.zeros([n,n], dtype = int)  #numpy 2d array of nxn elements 
    i=0
    counter=0
    #placing mines
    while i<num_of_mines:
        x= rm.randint(0,n-1)
        y= rm.randint(0,n-1)
        if matrix[x][y] == -10000:
            continue
        else: 
            matrix[x][y] = "-10000"
            i+=1    #'me' will be the point that moves in the matrix, it has only coordinates attributed to it
    me= [n-1,n-1]
    me_path=[]
    me_path.append(me)
    #choosing a number from 1 to 8 and depending on that we move "me" to the next block
    while counter<num_of_itr:
        #moving if "me" is at corners
        if me==[0,0]: #if me is at 0,0
            one_to_three=rm.randint(1,3)
            if one_to_three == 1:
                me=[me[0],me[1]+1]

            if one_to_three == 2:
                me=[me[0]+1,me[1]]
                
            if one_to_three == 3:
                me=[me[0]+1,me[1]+1]
                
        if me==[0,n-1]: #if me is at 0,n-1
            one_to_three=rm.randint(1,3)
            if one_to_three == 1:
                me=[me[0],me[1]-1]
                
            if one_to_three == 2:
                me=[me[0]+1,me[1]-1]
                
            if one_to_three == 3:
                me=[me[0]+1,me[1]]
            
        if me==[n-1,0]: #if me is at n-1,0
            one_to_three=rm.randint(1,3)
            if one_to_three == 1:
                me=[me[0]-1,me[1]]

            if one_to_three == 2:
                me=[me[0]-1,me[1]+1]
                
            if one_to_three == 3:
                me=[me[0],me[1]+1]
          
        if me==[n-1,n-1]: #if me is at n-1,n-1
            one_to_three=rm.randint(1,3)
            if one_to_three == 1:
                me=[me[0],me[1]-1]

            if one_to_three == 2:
                me=[me[0]-1,me[1]-1]
                
            if one_to_three == 3:
                me=[me[0]-1,me[1]]
        else:    
            one_to_eight= rm.randint(1,8)
            if one_to_eight == 1:
                me=[me[0]-1,me[1]-1]

            if one_to_eight == 2:
                me=[me[0]-1,me[1]]

            if one_to_eight == 3:
                me=[me[0]-1,me[1]+1]

            if one_to_eight == 4:
                me=[me[0],me[1]-1]

            if one_to_eight == 5:
                me=[me[0],me[1]+1]

            if one_to_eight == 6:
                me=[me[0]+1,me[1]-1]

            if one_to_eight == 7:
                me=[me[0]+1,me[1]]

            if one_to_eight == 8:
                me=[me[0]+1,me[1]+1]
        counter+=1
        me_path.append(me) 
        print(matrix,me_path)

In [21]:

#looking at the path of me
def me_trail_funct(n,me,me_path):
    me_matrix=np.zeros([n,n], dtype = int)
    me_start=me_path[0]
    for i in:
        

yay


In [65]:
iterations(10,8,10)

[[     0      0      0      0      0      0      0      0]
 [     0      0      0 -10000      0      0      0      0]
 [     0      0      0      0      0 -10000      0      0]
 [     0      0 -10000 -10000      0      0      0      0]
 [     0 -10000      0      0 -10000 -10000      0      0]
 [-10000      0      0      0      0      0      0      0]
 [     0      0      0 -10000      0      0      0      0]
 [     0      0      0      0      0      0 -10000      0]] [[7, 7], [7, 6]]
[[     0      0      0      0      0      0      0      0]
 [     0      0      0 -10000      0      0      0      0]
 [     0      0      0      0      0 -10000      0      0]
 [     0      0 -10000 -10000      0      0      0      0]
 [     0 -10000      0      0 -10000 -10000      0      0]
 [-10000      0      0      0      0      0      0      0]
 [     0      0      0 -10000      0      0      0      0]
 [     0      0      0      0      0      0 -10000      0]] [[7, 7], [7, 6], [8, 7]]
[[     0    