In [9]:
import numpy as np
import matplotlib.pyplot as pl
import random

n = 10
m = 10
start = [0,0]
end = [n-1 , n-1]
pos = start
path = [start]
mine_mem = []
edge_matr = np.concatenate(([-1] , np.zeros((n*n)-2 , dtype=int) , [-1])).reshape((n,n))

g = np.array([0] * ((n*n)-m-2) + [-555]*(m))
np.random.shuffle(g)
g = np.concatenate(([0] , g , [0]))
gr = np.reshape(g , (n,n))

      
def move():    
    global pos
    global path
    if (pos == [0,0]):
        pos = random.choice([[pos[0],(pos[1]+1)],[(pos[0]+1),pos[1]]])                
    elif (pos == [0,(n-1)]):
        pos = random.choice([[pos[0],(pos[1]-1)],[(pos[0]+1),pos[1]]])                
    elif (pos[0] == 0) and (pos[1]!=0) and (pos[1]!=(n-1)):
        pos = random.choice([[pos[0],(pos[1]-1)],[pos[0],(pos[1]+1)],[(pos[0]+1),pos[1]]])                           
    elif (pos == [(n-1),0]):
        pos = random.choice([[pos[0],(pos[1]+1)],[(pos[0]-1),pos[1]]])            
    elif (pos == [(n-1),(n-1)]):
        pos = random.choice([[pos[0],(pos[1]-1)],[(pos[0]-1),pos[1]]])
    elif ((pos[0] == (n-1)) and (pos[1]!=0) and (pos[1]!=(n-1))):
        pos = random.choice([[pos[0],(pos[1]-1)],[pos[0],(pos[1]+1)],[(pos[0]-1),pos[1]]])
    elif ((pos[1] == 0) and (pos[0]!=0) and (pos[0]!=(n-1))):
        pos = random.choice([[(pos[0]-1),pos[1]],[pos[0],(pos[1]+1)],[(pos[0]+1),pos[1]]])
    elif ((pos[1] == n-1) and (pos[0]!=0) and (pos[0]!=(n-1))):
        pos = random.choice([[(pos[0]-1),pos[1]],[pos[0],(pos[1]-1)],[(pos[0]+1),pos[1]]])
    else:
        pos = random.choice([[(pos[0]-1),pos[1]],[pos[0],(pos[1]+1)],[(pos[0]+1),pos[1]],[pos[0],(pos[1]-1)]])             
    path.append(pos)

while pos!=end and len(path)<=1000:
    if gr[pos[0],pos[1]] == -555 and pos not in mine_mem:
        mine_mem.append(pos)
        move()
    elif pos in mine_mem:
        pos = path[len(path)-2]
        del path[len(path)-1]
    elif gr[pos[0],pos[1]] != -555:
        move()
moves_num = len(path)
    
for i in range(n):
    for j in range(n):
        edge_matr[i,j] += 2*(list(path).count([i,j]))
            
print(gr, "\n" , "\n" , edge_matr, "\n", "\n" , path, "\n", "\n" , moves_num)

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0 -555    0    0    0    0    0    0 -555]
 [   0    0    0    0    0    0 -555 -555    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 -555    0    0 -555    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0 -555    0 -555    0    0    0    0]
 [-555    0    0    0    0    0    0 -555    0    0]] 
 
 [[33 34 38 44 32 22 26 22 22  6]
 [44 70 60 44 40 38 34 32 26 10]
 [30 52 36 32 34 50 42 40 32 14]
 [36 30  2 12 28 56 42 24 22  2]
 [32 20  8  8 16 20  2  0 14  4]
 [30 14  4  6 10 12 12 12 10  8]
 [12  6  2  8 10  2  4  4  2  8]
 [ 8  8  4  6  8  2  8  4  4  8]
 [ 6 10  2  2  6  2  6  2  0  4]
 [ 2  4  0  0  2  2  2  2  0  1]] 
 
 [[0, 0], [0, 1], [0, 2], [1, 2], [1, 1], [1, 2], [0, 2], [0, 3], [0, 4], [1, 4], [1, 5], [2, 5], [1, 5], [2, 5], [2, 6], [3, 6], [